const data = {
  tasks: [
    {
      title: 'Creating Awesome Mobile Apps 1',
      description: 'Item 1',
      category: 'UI UX Design',
      progress: 10,
      dueDate: '',
      asignee: [],
      mentor: [],
      images: [],
    },
    {
      title: 'Creating Awesome Mobile Apps 2',
      description: 'Item 1',
      category: 'UI UX Design',
      progress: 10,
      dueDate: '',
      asignee: [],
      mentor: [],
      images: [],
    },
    {
      title: 'Creating Awesome Mobile Apps 3',
      description: 'Item 1',
      category: 'UI UX Design',
      progress: 10,
      dueDate: '',
      asignee: [],
      mentor: [],
      images: [],
    },
    {
      title: 'Creating Awesome Mobile Apps 4',
      description: 'Item 1',
      category: 'UI UX Design',
      progress: 10,
      dueDate: '',
      asignee: [],
      mentor: [],
      images: [],
    },
    {
      title: 'Creating Awesome Mobile Apps 5',
      description: 'Item 1',
      category: 'UI UX Design',
      progress: 10,
      dueDate: '',
      asignee: [],
      mentor: [],
      images: [],
    },
    {
      title: 'Creating Awesome Mobile Apps 6',
      description: 'Item 1',
      category: 'UI UX Design',
      progress: 10,
      dueDate: '',
      asignee: [],
      mentor: [],
      images: [],
    },
  ],
};

export default data;
